<section>
    <div class="container">
        <div class="row">
<?php foreach($params['posts'] as $post): ?>   
            <div class="col-md-8 offset-md-2">    
                <h2><?= $post['title'] ?></h4>
                <p><?= $post['body'] ?></p>
                <a href="/comments?postId=<?= $post['id']?>">Comments</a>
            </div>
<?php endforeach?>    
        </div>
    </div>
</section>
