<?php
//Input data check
$postType = $_POST['type'] ?? "";
?>

<!-- 
    Resources list we could print out with every data
    for https://jsonplaceholder.typicode.com/ + every type of query. + https://fakestoreapi.com/users

    Options have the selected checking as well
-->
<section name="resourcesForm">
    <div class="container mt-4">

        <form action="/resources" method="POST" class="form-inline">
            <div class="col-md-6 mb-3">
                <label for="resourceType" class="form-label">Select Resource Type:</label>
                <select name="type" id="resourceType" class="form-select" required>
                    <option value="/posts" <?= ($postType==="/posts" ? "selected" : "")?>>Posts</option>
                    <option value="/comments" <?= ($postType==="/comments" ? "selected" : "")?>>Comments</option>
                    <option value="/albums" <?= ($postType==="/albums" ? "selected" : "")?>>Albums</option>
                    <option value="/photos" <?= ($postType==="/photos" ? "selected" : "")?>>Photos</option>
                    <option value="/todos" <?= ($postType==="/todos" ? "selected" : "")?>>Todos</option>
                    <option value="/users" <?= ($postType==="/users" ? "selected" : "")?>>Users</option>
                    <option value="https://fakestoreapi.com/users" <?= ($postType==="https://fakestoreapi.com/users" ? "selected" : "")?>>Login</option>
                </select>
            </div>
            <div class="col-md-6">
                <button type="submit" class="btn btn-primary">Do it</button>
            </div>
        </form>
    </div>
</section>
<!-- 
    Shows which data we used before with POST
    show the selected database which processed before on index.php and we get as params['content']
-->
<section name="responseField">
    <div class="container mt-4">
        <?php
        if (isset($_POST['type'])) {
            echo '<br>POST: <pre>';
            var_dump($_POST);
            echo '<br>RESPONSE: <pre>';
            var_dump($params['content']);
        }
        ?>
    </div>
</section>