<?php
    //https://fakestoreapi.com/users
    //https://dummy.restapiexample.com/api/v1/employees
    //http://404.php.net/
    $url_dummy ="https://dummy.restapiexample.com/api/v1/employees";
    $url_fake_all="https://fakestoreapi.com/users";
    $url_error ="http://expamle.com";
    $url_http_error="http://example.com/whatever";
    $url_ok = "http://example.com";

    $userData =
        array (
            'email' => 'John@gmail.com',
            'username' => 'johndd',
            'password' => 'm38rmF$',
            'name' => 
            array (
                'firstname' => 'John',
                'lastname' => 'Doe',
            ),
            'address' => 
            array (
                'city' => 'kilcoole',
                'street' => '7835 new road',
                'number' => 3,
                'zipcode' => '12926-3874',
                'geolocation' => 
                array (
                'lat' => '-37.3159',
                'long' => '81.1496',
                ),
            ),
            'phone' => '1-570-236-7033',
        );
    $url = "https://fakestoreapi.com/users/10";


