<?php 
$userAPI = json_decode(file_get_contents("https://fakestoreapi.com/users"),true);



try {
    $pdo = new PDO(
        'mysql:host=' . $_SERVER['DB_HOST'] . ';dbname='. $_SERVER['DB_NAME'], 
        $_SERVER['DB_USER'],
        $_SERVER['DB_PASSWORD']
    );
    $rresult = $pdo -> query('SELECT * FROM `dsa`');
} catch (PDOException $e) {
    echo "baj: <pre>";
    var_dump($e);
    

}
//CREATE TABLE `users` ( `id` int NOT NULL, `email` varchar(255) NOT NULL, `username` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `firstname` varchar(255) NOT NULL, `lastname` varchar(255) NOT NULL, `city` varchar(255) NOT NULL, `street` varchar(255) NOT NULL, `number` int NOT NULL, `zipcode` varchar(255) NOT NULL, `geoLat` float NOT NULL, `geoLong` float NOT NULL, `phone` varchar(255) NOT NULL);


?>
