<?php 
//existsTable
//createTable // ALTER TABLE // //uploadTableData
//existsTableData
//uploadTableData
$table="test";
echo "<pre>";

/**
 * Check if the table is exists
 * if not, create that
 */
var_dump(checkUsersTable());
exit;

if (!checkTable($table)) {
    echo "<br>wrong";
    exit;    
}
echo "<br>Table exists ";
var_dump(checkTable($table));

if (!checkTableData($table)){
    echo "<br>wrong";
    exit; 
}
echo "<br>Data exists ";
var_dump(checkTableData($table));

echo "<br>Data source ";
var_dump(userCount());

if (checkTableData($table) != (userCount())) {
    echo "Data not same";
}

echo "<br>win";

function getUserById(){

}

function editUserById(){

}

function deleteUserById(){

}

function createUser(){

}

function getConnection(){

}


function checkTableData($tableName){
    try {
        $pdo = new PDO(
            'mysql:host=' . $_SERVER['DB_HOST'] . ';dbname='. $_SERVER['DB_NAME'], 
            $_SERVER['DB_USER'],
            $_SERVER['DB_PASSWORD']
        );
        
        $sql = "SELECT * FROM `".$tableName."`";
        $res = $pdo->query($sql);
        $count = $res->fetchColumn();

        if (!$count) {
            return false;
        }
        return $count;

    } catch (PDOException $pdoe) {
        return false; 
    }
}

function userCount(){
    $usersAPI = json_decode(file_get_contents("https://fakestoreapi.com/users"),true);
    return count($usersAPI);
}

function store(){/*

    $id = array_column($usersAPI,"id");
    array_multisort($id, SORT_ASC, $usersAPI);
    echo '<pre>';
    foreach ($usersAPI as $user) {

        var_dump($user); 
    }

    if (!$tableEx) {
        createUserTable();
    } 

    $sql1 = "SELECT * FROM `".$tableName."`";
    $stmt =  $pdo->prepare($sql1);
    try{
        $stmt->execute();
        $dataEx = $stmt->fetchColumn();
    } catch (PDOException $e) {
        die("<br>Tábla adat ellenőrzés hibája: " . $e->getMessage());
    }
    if (!$dataEx) {
        # code...
    }
*/
}



function checkUsersTable(){
    try {
        $sql = "CREATE TABLE `users` (
            `id` int NOT NULL ,
            `email` varchar(255) NOT NULL,
            `username` varchar(255) NOT NULL,
            `password` varchar(255) NOT NULL,
            `firstname` varchar(255) NOT NULL,
            `lastname` varchar(255) NOT NULL,
            `city` varchar(255) NOT NULL,
            `street` varchar(255) NOT NULL,
            `number` int NOT NULL,
            `zipcode` varchar(255) NOT NULL,
            `geoLat` float NOT NULL,
            `geoLong` float NOT NULL,
            `phone` varchar(255) NOT NULL,
            `uploaded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (`id`)
        )";

        $pdo = new PDO(
            'mysql:host=' . $_SERVER['DB_HOST'] . ';dbname='. $_SERVER['DB_NAME'], 
            $_SERVER['DB_USER'],
            $_SERVER['DB_PASSWORD']
        );

        $stmt =  $pdo->prepare($sql);
        try {
            $result = $stmt->execute();
            return $result;
        } catch (PDOException $e) {
            $errorCode = $e->errorInfo[0];
            if ($errorCode === '42S01') {
                // Itt kezeld a várt hibakódot
                echo "A tábla már létezik.";
            } else {
                // Kezeld az egyéb hibakódokat vagy dobj további kivételt
                die("Hiba: " . $e->getMessage());
            }
        }
    } catch (PDOException $e) {
        return false;
    }
}


function checkTable($tableName){
    /** Journey around creating tables
     * Original plan was: Make sure the table is already exists, 
     * if not, not problem, creat it and fill it up with the data.
     * First I tried with check the table is exists, then if not create that
     * but I rememberd IF NOT EXISTS selectorwould functionally perfect for here
     * but as resoult I couldnt check, table was exists before.
     * then I had a siply idea, so I made a normal create table and with error handling 
     * I could see, it was exists (error but not funcion not die), if wasnt exists just normally created!
     */
    $pdo = new PDO(
        'mysql:host=' . $_SERVER['DB_HOST'] . ';dbname='. $_SERVER['DB_NAME'], 
        $_SERVER['DB_USER'],
        $_SERVER['DB_PASSWORD']
    );
    
    $sql = "SELECT 1 FROM information_schema.tables 
        WHERE table_schema = database() AND table_name = ?";
    $stmt =  $pdo->prepare($sql);
    try {
        $stmt->execute([$tableName]);
        $tableEx = (bool)$stmt->fetchColumn();
        if ($tableEx) {
            return true;
        }
    } catch (PDOException $e) {
        die("<br>Tábla létezés ellenőrzés hibája: " . $e->getMessage());
    }
}
?>

