<?php
function getUserById($id){
    $pdo = getConnection();

}

function editPostById(){

}

function deletePostById(){

}

function createUser(){

}

// Kiegészítő funkció részleg

function checkDB(){
    /**
     * Table exists? , Data was valid?
     * True - True = Early exit.
     * True - False = uploadBulkData
     * False - null = in checkUsersTable() the empty table will created. 
     * Last both case needs 'uploadBulkData'
     * It wont duplicate the data, by "id", log out every uploaded data.
     */
    $pdo = getConnection();
    try {
        if (checkUsersTable($pdo)) {
            if (checkUsersData($pdo)) {
            logJS("Table, data check was successfully");
            }
         }
         uploadBulkData($pdo);
    } catch (Exception $e) {
        logJS("Hiba: ", $e->getMessage());
    }finally{
        $pdo = NULL;
    }
}

function uploadBulkData($pdo){
    //Get the API source data
    $usersAPI = json_decode(file_get_contents("https://fakestoreapi.com/users"),true);

    //log data about how many user was uploaded
    $idLog = [
        'count' => 0,
        'user' => []
    ];

    /** ON DUPLICATE
     * kulcs alapján ellenőrzi, ez a record létezik-e már az adott táblában.
     */
    $sql = 'INSERT INTO users(id,email,username,pwd,phone) 
        VALUES(:id,:email,:username,:pwd,:phone) 
        ON DUPLICATE KEY UPDATE id = :id';

    /** Transaction
     * Használata, tekintve hogy több tranzakció is lefut, érdemes megfigyelni hogy jól futnak-e le.
     * beginTransaction megynitni, commital zárni és hibakezelésként rollbackelni, visszavonni. 
     */
    try {
        $pdo->beginTransaction();
        $statement = $pdo->prepare($sql);

        foreach ($usersAPI as $user) {
            $statement->execute([
                ':id' => $user['id'],
                ':email' => $user['email'],
                ':username' => $user['username'],
                ':pwd' => $user['password'],
                ':phone' => $user['phone'],
            ]);
            /** ON DUPLICATE
             * Amennyiben van érték, akkor annak adatait idLogba eltároljuk
             * Végén kiiratjuk 
             */
            if ((bool)$statement->rowCount()) {
                array_push($idLog['user'],$user);
                $idLog['count']++;
            }
        }
        $pdo->commit();
        if($idLog['count'] > 0){
            logJS("Data uploaded:",$idLog);
        } 
    } catch (PDOException $e) {
        $pdo->rollBack();
        logJS("<br>Data upload error: ", $e->getMessage());
    }
}

function userCount(){
    //Original source of data API call and gives back the count of them
    $usersAPI = json_decode(file_get_contents("https://fakestoreapi.com/users"),true);
    return count($usersAPI);
}

function checkUsersData($pdo){
    /**
     * -Get the number of data, what the users table have
     * -Get the number of data of API source and compare and check if the SQL data is uptodate
     */
    try {
        //COUNT the number of result
        $sql = "SELECT COUNT(*) FROM `users`";
        
        $res = $pdo->query($sql);
        $columns = $res->fetchColumn();

        //original data source, number of data
        $srcCount = userCount();  

        if ($srcCount === $columns) {
            return true;
        } else {
            logJS("Data mismatch");
            return false;
        }
    } catch (PDOException $e) {
        logJS("User check error: ",$e->getMessage());
        exit;
    }
}

function checkUsersTable($pdo){

    /**
     * Biztosra kell mennünk hogy a tábla létezik
     * Amennyiben létezik PDOExceptionnal visszatér és fix hibakód alapján azonosítva továbblépünk
     * Ha minden lefut, akkor létrejön de tudjuk hogy üres a táblánk.
     */
    try {
        $sql = "CREATE TABLE `users` (
            `id` int NOT NULL ,
            `email` varchar(255) NOT NULL,
            `username` varchar(255) NOT NULL,
            `pwd` varchar(255) NOT NULL,
            `phone` varchar(255) NOT NULL,
            PRIMARY KEY (`id`)
        )";

        $stmt =  $pdo->prepare($sql);
        try {
            //if the table created then it's empty, later we need to 'uploadBulkData' 
            $stmt->execute();
            logJS("Table created");
            return false;
        } catch (PDOException $e) {
            $errorCode = $e->errorInfo[0];
            //if the table was already exist - CREATE TABLE errorCode: '42S01' 
            if ($errorCode === '42S01') {
                return true;
            } else {
                logJS("Table create error: ", $e->getMessage());
                exit;
            }
        }
    } catch (PDOException $e) {
        logJS("Table check error: ",$e->getMessage());
        exit;
    }
}

function getConnection(){
    try {
        $pdo = new PDO ( 
            'mysql:host='.$_SERVER['DB_HOST'].';dbname='.$_SERVER['DB_NAME'],
            $_SERVER['DB_USER'],
            $_SERVER['DB_PASSWORD']
        );
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        return $pdo;
    } catch (Exception $e) {
        logJS("PDO Connection error:", $e);
        return null;
    }
}

function logJS(...$dataArray){
    //Params: if I want to Give a string before, or multiply data to log in a same time, then I have to use '...' 
    /**I wanted to see through my code, which phases works, results etc.
     * echo and var_dump works fine but after a while, these looks little trashy, toomuch information.
     * I wanted to follow my workflow easy-to-read, and if it's possible, I want to avoid
     * write the status to the view - so I wanted to use the console for development.
     */
    
    foreach ($dataArray as  $data) {
        if ($data instanceof Exception) {
            //In Exception case, we get the Error message
            echo '<script>console.log('.json_encode($data->getMessage()).');</script>';
        }else {
            //or just we want to check some data, sometimes easier to read then var_dump
            echo '<script>console.log('.json_encode($data).');</script>';
        }
    }
}