<section>
    <div class="container mt-4">
        <form action="/login" method="POST" class="col-md-6 offset-md-3">
            <h2 class="mb-4">Login</h2>

            <div class="mb-3">
                <label for="username" class="form-label">username:</label>
                <input type="text" name="username" id="username" class="form-control" value="mor_2314" required>
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Password:</label>
                <input type="password" name="password" id="password" class="form-control" value="83r5^_" required>
            </div>

<?php if(isset($_GET['info']) && $_GET['info']==="invalidCredentials"):?>
                <div class="mb-3" class="">
                    <label for="password" class="form-label">Wrong</label>
                </div>
<?php endif?>

            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</section>