<div class="container">
    <h2>Regisztráció űrlap</h2>
    <form method="POST" action="/register">
        <div class="form-group">
            <label for="email">Email cím:</label>
            <input type="email" class="form-control" id="email" name="email" value="kerek@kerek.com" required>
        </div>
        <div class="form-group">
            <label for="username">Felhasználónév:</label>
            <input type="text" class="form-control" id="username" name="username" value="dani" required>
        </div>
        <div class="form-group">
            <label for="password">Jelszó:</label>
            <input type="password" class="form-control" id="password" name="password" value="dadad" required>
        </div>
        <div class="form-group">
            <label for="phone">Telefonszám:</label>
            <input type="tel" class="form-control" id="phone" name="phone" value="+3123312312"required>
        </div>
        <button type="submit" class="btn btn-primary">Regisztráció</button>
    </form>
</div>